### ISSUE TITLE
Internal Server Issue

### ISSUE THREAD

**Issue by arbusam** [sweharris/Alexa-Smart-Home-VirtualButtons#3]
I know this is an old repo but whenever I try to access the API I get this: `{
    "message": "Internal Server Error"
}`

**Comment by arbusam** [comment]
Ok I looked for some logs and I found a more specific error: `23.3.84.108 - - [12/Feb/2023:06:11:07 +0000] "POST ANY /Smart_Home_Virtual_Buttons HTTP/1.1" 500 35 ANlnRjAmoAMEanQ=The response from the Lambda function doesn't match the format that API Gateway expects. Lambda body is invalid JSON`

**Comment by sweharris** [comment]
(The reason this repo looks old is because "it just works"; I've not needed to touch it.  It's in active use on my account :-) )

What activity are you doing to generate that error?  That IP address is an Akamai one, so it _looks_ that you have some software making an HTTP request to the API gateway?

There should be a lot more logs generated than just the one line.  You should post the whole session from lambda function start through to completion  (redacting any secrets, such as tokens and host URL and authorization strings).

e.g. here's a call my system generated on Friday

```
2023/02/10 18:45:39 Handler started
2023/02/10 18:45:39 API call
2023/02/10 18:45:39 
{
    "version": "2.0",
    "routeKey": "ANY /Smart_Home_Virtual_Buttons",
    "rawPath": "/Smart_Home_Virtual_Buttons",
    "rawQueryString": "",
    "headers": {
        "accept": "*/*",
        "accept-encoding": "gzip, deflate",
        "authorization": "XX",
        "content-length": "72",
        "content-type": "application/octet-stream",
        "host": "XXXXXXXXXX.execute-api.us-east-1.amazonaws.com",
        "user-agent": "HomeAssistant/2021.10.6 aiohttp/3.7.4.post0 Python/3.9",
        "x-amzn-trace-id": "Root=1-63e690d3-75c942dc3eeea7a55a6fc00c",
        "x-forwarded-for": "108.5.17.173",
        "x-forwarded-port": "443",
        "x-forwarded-proto": "https"
    },
    "requestContext": {
        "accountId": "186116053575",
        "apiId": "XXXXXXXXXX",
        "domainName": "XXXXXXXXXX.execute-api.us-east-1.amazonaws.com",
        "domainPrefix": "XXXXXXXXXX",
        "http": {
            "method": "POST",
            "path": "/Smart_Home_Virtual_Buttons",
            "protocol": "HTTP/1.1",
            "sourceIp": "108.5.17.173",
            "userAgent": "HomeAssistant/2021.10.6 aiohttp/3.7.4.post0 Python/3.9"
        },
        "requestId": "AIuRDjZOoAMEZ9A=",
        "routeKey": "ANY /Smart_Home_Virtual_Buttons",
        "stage": "$default",
        "time": "10/Feb/2023:18:45:39 +0000",
        "timeEpoch": 1676054739246
    },
    "body": "eyJjb21tYW5kIjogInNldHN0YXRlYnluYW1lIiwgInBhcmFtMSI6ICJHYXJhZ2UgQnV0dG9uIiwgInBhcmFtMiI6ICIwIiB9",
    "isBase64Encoded": true
}

2023/02/10 18:45:39 Body is: eyJjb21tYW5kIjogInNldHN0YXRlYnluYW1lIiwgInBhcmFtMSI6ICJHYXJhZ2UgQnV0dG9uIiwgInBhcmFtMiI6ICIwIiB9
2023/02/10 18:45:39 Decoded body: 
{
    "command": "setstatebyname",
    "param1": "Garage Button",
    "param2": "0"
}

2023/02/10 18:45:39 Pushing a notification to Alexa
2023/02/10 18:45:39 No refresh needed
2023/02/10 18:45:39 
{
    "event": {
        "header": {
            "namespace": "Alexa",
            "name": "ChangeReport",
            "messageId": "b67dc5dc-5dea-4365-8065-89e5ec858522",
            "payloadVersion": "3"
        },
        "endpoint": {
            "scope": {
                "type": "BearerToken",
                "token": "XXXXX"
            },
            "endpointId": "switch-000010"
        },
        "payload": {
            "change": {
                "cause": {
                    "type": "PHYSICAL_INTERACTION"
                },
                "properties": [
                    {
                        "namespace": "Alexa.ContactSensor",
                        "name": "detectionState",
                        "value": "NOT_DETECTED",
                        "timeOfSample": "2023-02-10T18:45:39.325739964Z",
                        "uncertaintyInMilliseconds": 0
                    }
                ]
            }
        }
    },
    "context": {
        "properties": [
            {
                "namespace": "Alexa.EndpointHealth",
                "name": "connectivity",
                "value": {
                    "value": "OK"
                },
                "timeOfSample": "2023-02-10T18:45:39.325739964Z",
                "uncertaintyInMilliseconds": 0
            }
        ]
    }
}

2023/02/10 18:45:39 Body response: 
2023/02/10 18:45:39 Handler ended: 
{
    "Answer:": "Update Success"
}
```

**Comment by arbusam** [comment]
I don't know if I said this properly but the skill was downloaded correctly. When I try to add a button using the curl command, it fails. Whenever I try I get this in the logs: `

INIT_START Runtime Version: go:1.v13	Runtime Version ARN: arn:aws:lambda:us-east-1::runtime:3f96445bbbd5587be5ace0de37b48e731074fa350870a8a3cb87f45011d70281
--
2023/02/13 06:36:24 Lambda started
START RequestId: 1885921b-caf7-491e-b865-20f4acca583d Version: $LATEST
2023/02/13 06:36:24 Handler started
2023/02/13 06:36:24 Handler ended: No results
END RequestId: 1885921b-caf7-491e-b865-20f4acca583d
REPORT RequestId: 1885921b-caf7-491e-b865-20f4acca583d	Duration: 4.81 ms	Billed Duration: 5 ms	Memory Size: 128 MB	Max Memory Used: 36 MB	Init Duration: 117.94 ms

`

**Comment by arbusam** [comment]
I don't know if I said this properly but the skill was downloaded correctly. When I try to add a button using the curl command, it fails. These are the logs I get:
`
INIT_START Runtime Version: go:1.v13	Runtime Version ARN: arn:aws:lambda:us-east-1::runtime:XXXXXXXX
2023/02/13 06:36:24 Lambda started
START RequestId: 1885921b-caf7-491e-b865-20f4acca583d Version: $LATEST
2023/02/13 06:36:24 Handler started
2023/02/13 06:36:24 Handler ended: No results
END RequestId: 1885921b-caf7-491e-b865-20f4acca583d
REPORT RequestId: 1885921b-caf7-491e-b865-20f4acca583d	Duration: 4.81 ms	Billed Duration: 5 ms	Memory Size: 128 MB	Max Memory Used: 36 MB	Init Duration: 117.94 ms


`

**Comment by sweharris** [comment]
OK, this is the interesting bit...

```
2023/02/13 06:36:24 Handler started 
2023/02/13 06:36:24 Handler ended: No results 
```

This is coming from `process_lambda()` in `handler.go`

```
        log.Println("Handler started")

        // We'll initially just map the incoming data to an array.  This will
        // let us easily look at the fields at the top of the JSON structure
        // and make a guestimate as to the type of call.

        result := "No results"

        var req map[string]interface{}
        err := json.Unmarshal(data, &req)

        if err != nil {
                result = "Bad parse: " + err.Error()
                log.Println("Bad parse: " + err.Error())
        } else if req["directive"] != nil {
                log.Println("Alexa call")
                result = handle_alexa(data)
        } else if req["routeKey"] != nil {
                log.Println("API call")
                result = api_wrapper(data)
        }

        log.Println("Handler ended: " + result)
```

This means we have valid JSON data (or potentially no data?  I'm not sure) but we're not seeing a "directive" or "routeKey" entry, so the code doesn't know what to do with it.  We're not even seeing the  "Alexa call" or "API call" to show it was picking a branch.

Are you using `curl` on Unix or on Windows using powershell's curl cocmmand?   Can you paste the `curl` command you're using (with secrets and unique URL front masked).

Do you have the tools to compile go code yourself?  If so I'd recommend putting a line such as

```
log.Println("Incoming data: ",string(data))
```

before the `result := ...` line.  That should show us the raw incoming request.   Compile that (`make lambda.zip`) and replace the lambda with the new zip file.  If you can't then I can build an (untested) version and stick it somewhere for you to download.

**Comment by arbusam** [comment]
I am on a mac using curl and this is my command: `curl https://XXXXXXX.execute-api.us-east-1.amazonaws.com/default/Smart_Home_Virtual_Buttons -d '{"command":"setname", "param1":"1", "param2": "Turn on lights"}'`. I tried to build the go file but I have absolutely no experience with anything of that source and my print didn't appear in the logs. I would greatly appreciate it if you can help by compiling a new zip that I could use (maybe in another branch).

**Comment by arbusam** [comment]
Thank you so much for this. I managed to successfully upload it and now I have the logs. I have put them below.
`{
    "version": "1.0",
    "resource": "/Smart_Home_Virtual_Buttons",
    "path": "/default/Smart_Home_Virtual_Buttons",
    "httpMethod": "POST",
    "headers": {
        "Content-Length": "63",
        "Content-Type": "application/x-www-form-urlencoded",
        "Host": "XXXXX.execute-api.us-east-1.amazonaws.com",
        "User-Agent": "curl/7.86.0",
        "X-Amzn-Trace-Id": "Root=1-63ec89dd-620ba8c85a56bfb859df8a56",
        "X-Forwarded-For": "123.3.84.108",
        "X-Forwarded-Port": "443",
        "X-Forwarded-Proto": "https",
        "accept": "*/*"
    },
    "multiValueHeaders": {
        "Content-Length": [
            "63"
        ],
        "Content-Type": [
            "application/x-www-form-urlencoded"
        ],
        "Host": [
            "XXXXX.execute-api.us-east-1.amazonaws.com"
        ],
        "User-Agent": [
            "curl/7.86.0"
        ],
        "X-Amzn-Trace-Id": [
            "Root=1-63ec89dd-620ba8c85a56bfb859df8a56"
        ],
        "X-Forwarded-For": [
            "123.3.84.108"
        ],
        "X-Forwarded-Port": [
            "443"
        ],
        "X-Forwarded-Proto": [
            "https"
        ],
        "accept": [
            "*/*"
        ]
    },
    "queryStringParameters": null,
    "multiValueQueryStringParameters": null,
    "requestContext": {
        "accountId": "XXXXX",
        "apiId": "XXXXX",
        "domainName": "XXXXX.execute-api.us-east-1.amazonaws.com",
        "domainPrefix": "XXXXX",
        "extendedRequestId": "AXp6rhqBoAMEYmA=",
        "httpMethod": "POST",
        "identity": {
            "accessKey": null,
            "accountId": null,
            "caller": null,
            "cognitoAmr": null,
            "cognitoAuthenticationProvider": null,
            "cognitoAuthenticationType": null,
            "cognitoIdentityId": null,
            "cognitoIdentityPoolId": null,
            "principalOrgId": null,
            "sourceIp": "123.3.84.108",
            "user": null,
            "userAgent": "curl/7.86.0",
            "userArn": null
        },
        "path": "/default/Smart_Home_Virtual_Buttons",
        "protocol": "HTTP/1.1",
        "requestId": "AXp6rhqBoAMEYmA=",
        "requestTime": "15/Feb/2023:07:29:33 +0000",
        "requestTimeEpoch": 1676446173638,
        "resourceId": "ANY /Smart_Home_Virtual_Buttons",
        "resourcePath": "/Smart_Home_Virtual_Buttons",
        "stage": "default"
    },
    "pathParameters": null,
    "stageVariables": null,
    "body": "eyJjb21tYW5kIjoic2V0bmFtZSIsICJwYXJhbTEiOiIxIiwgInBhcmFtMiI6ICJUdXJuIG9uIGxpZ2h0cyJ9",
    "isBase64Encoded": true
}
`

**Comment by arbusam** [comment]
You might want to put this in a JSON Viewer (I recommend JSON Viewer Awesome which is a chrome extension). Just realised how ugly JSON looks on GitHub.

**Comment by sweharris** [comment]
(I think the ugly JSON is a consequence of cut'n'paste from cloudwatch; I find that if I paste into a vi session and then cut'n'paste _that_ into github then it looks fine.  Heh.  It shows up cleanly in the email notification, though!)

OK, so this is interesting.  Your request is showing a version 1.0 whereas mine is version 2.0.  I wonder if there's some API gateway version toggle.  Anyway... I think the important fields are unchanged, so I've pushed a new version that should (fingers crossed) also detect this json version and process it.

Let's hope this one works for you :-)

**Comment by arbusam** [comment]
When I run the command for some reason I still get the Internal server error in my console but after checking the logs everything is working. Thank you so much for your help but I have one more error. I have two buttons created but for some reasonn the alexa app keeps saying that there are no new devices found and nothing shows up in the logs.

**Comment by sweharris** [comment]
I can think of some possibilities.

If nothing is showing in the logs at all then the lambda isn't being triggered.  Maybe you haven't completed the linkage between the Alexa skill and the lambda.  This could be because you didn't define the trigger properly (perhaps wrong skill ARN?) or you didn't add the lambda ARN to the "smart home" tab i the skill devevloper console.

Or perhaps you didn't turn on "send alexa events" in the permissions tab?

There's so many fiddly bits to configure to get this working correctly that it's easy to have missed a step.  I did retest the process back in September on a test account and it worked, but it is fiddly!

Or perhaps the language doesn't match the language of your Alexa?  I'm in the US but I have my Alexa devices configured for UK English (since I'm an Englishman but living in America) so I defined this skill for English(UK).  I know this is important for voice activated skills, but I have no idea if it's important for smart home skills.
  
Or (and this is the bit I'm not sure of) you deployed to the wrong region.  I don't know if this matters.  My Alexa is in the US (although set to UK English) and it talks to the lambda in us-east-1 just fine.  It shouldn't matter 'cos we select "global endpoint" but I just can't test this.
